### PR TITLE
Grails web-api profile candidate

### PR DESCRIPTION
**Pull request by akarazniewicz**
Hi

Please consider adding this 'web-api' profile to official Grails profile repository. I believe this is obvious candidate between full blown 'web' profile and 'web-minimal'. This is stripped down web profile for exposing web APIs through Grails web service capabilities. Compared to full 'web' profile this one:

* doesn't have 'views' capability (nor gsp plugin, view-related commands, no assets pipeline etc.)
* has controllers exposing JSON messages for HTTP 500 and 404 (similar to notFound.gsp and error.gsp) in 'web' profile
* has an IndexController with a welcome message similar to original one, however exposed as a JSON message.

### CODE REVIEW

**Comment by dmahapatro** [comment]
+1

**Comment by srimajji** [comment]
:+1:

**Comment by biniama** [comment]
+100

**Comment by graemerocher** [comment]
Still being reviewed, although the `build.gradle` pulls in `grails-dependencies` which would pull in all of GSP etc. which seems unnecessary for this profile?

**Comment by dmahapatro** [comment]
@akarazniewicz / @graemerocher Any plans to work on this further? I feel this profile will be a great selling point in enterprise. It is, actually at my work place. Our UI component (AngularJS) hosted in Grails is now moving to Node.js. Server side component will either be in Spring Boot or Grails 3. I am trying hard to convince client to adopt Grails 3 instead of Spring Boot because of the plugin eco-system which Grails 3 would provide. (This is also a reason why I wanted to involve myself in transitioning prioritized plugins from older version of Grails to Grails 3 compatible).

With this profile, I believe I can add more weightage to my point in order to adhere to Grails 3 instead of plain vanilla Spring Boot. 

Please comment.

**Comment by graemerocher** [comment]
@dmahapatro We are working on a single page web app / REST profile, @jeffbrown can comment but yes this is definitely something we want to include and we will address this pull request shortly

**Comment by dmahapatro** [comment]
Thanks @graemerocher and @jeffbrown . Let me know if I can be of any help in any way possible.

**Comment by akarazniewicz** [comment]
@dmahapatro Hope after review this profile will end up in official profile repository. However this is just profile, essentially stripped down configuration of grails, If You already have application, this addition - while nice, I believe - may have secondary value to You.

**Comment by dmahapatro** [comment]
@akarazniewicz Agree, but in the process of transition from Grails 2 to Grails 3 or Spring Boot, it will be helpful for me to sell the idea of moving to Grails 3 because of this profile which fits to the enterprise need the most. :)

**Comment by ortimanu** [comment]
This will be a great addition to the Grails 3 profiles! I use Grails 90% of the time just for RESTful services. And I always end up removing all the extra gsp stuff and related. Please merge whenever you can.

**Comment by abdielou** [comment]
+1k

**Comment by hussainanjar** [comment]
:+1:

**Comment by Omnipresent** [comment]
+1 for single page web app / REST profile

**Comment by jeffbrown** [comment]
> +1 for single page web app / REST profile

I don't think those 2 should be conflated.  They have things in common, but there will be folks who want one without the other.  I think an SPA profile makes sense and that would include REST optimizations and separate from that I think there is a desire to have a REST profile.

**Comment by Omnipresent** [comment]
@jeffbrown has the work began on SPA profile? Just wanted to see the code. Thanks

**Comment by jeffbrown** [comment]
> has the work began on SPA profile? Just wanted to see the code.

Yes.  There is no code but we have had design meetings recently.  When code is written we will make that known.  I expect some of that to start emerging soon.

**Comment by orubel** [comment]
Its a good temporary profile for single instance api. Not appropriate for distributed architecture

**Comment by jeffbrown** [comment]
@orubel 

> Its a good temporary profile for single instance api.

I don't think that this profile (or group of profiles that come out of this) will be temporary.  I expect that when finished they will be published and we be out there in perpetuity.

> Not appropriate for distributed architecture

There are a lot of things that are not appropriate for a distributed architecture.  Are you just pointing out that this is one, or are you addressing something else?

I am just trying to clarify what it is you are saying.

Thanks for the feedback.

**Comment by orubel** [comment]
Well it's a pattern wherein app dev has always been for single instances and patterns have always been for single instances as well but in modern architectures, these patterns have changes as well as our developments habits but our developments patterns and habits haven't so we still design and build for single instances and then have to MANUALLY change and rewrite for distributed architectures.

What should be the case is that the design and patterns should be adapted so that regardless of a single instance or distributed architecture, patterns fit both designs. Make sense?

**Pull request merged**
