### PR TITLE
Fix grails-core issue #9018 - Unable to create SSL cert w/ jdk8

### PR DESCRIPTION
**Pull request by ikakara**
Fix for https://github.com/grails/grails-core/issues/9018 - Grails 3 w/ jdk8 (in Windows) can't create SSL cert

Works in Grails 2.5.x (jdk8 in Windows); And also works w/ Grails 3 (jdk7 in Windows).
 
Graeme pointed me to Grails 2.5.x code, https://github.com/grails-plugins/grails-tomcat-plugin/blob/master/src/groovy/org/grails/plugins/tomcat/TomcatServer.groovy#L208 , which I copied to 3.x

I didn't test it - not sure how.  It would be nice if this project was a gradle project, for testing, etc

Allen

### CODE REVIEW

**Comment by ikakara** [comment]
@graemerocher - the initial checkin was just a straight copy from the 2.5.x (working code) to 3.x.  But I noticed that you wrapped w/ try/catch to return null instead of exception (on failure).  I updated the pull request to reflect that.

Hopefully, this fix can go into the next release.  Adds the check for Sun JDK8, then pre-JDK8, then non-Sun JDKs.

Allen

**Comment by graemerocher** [comment]
@ikakara Would you mind sending the pull request to the 3.0.x branch? Thanks.

**Comment by ikakara** [comment]
@graemerocher - sure I don't mind. 

How do I do that?  Do I have to create another pull request from grails-profile-repository (and send it using a setting to grails 3.x) or is this project mirror'd grails-core somewhere and I make the changes in grails-core?

**Comment by graemerocher** [comment]
I sorry ignore me thought this was against the 'grails-core' repo

**Comment by ikakara** [comment]
Great - it's a Friday, so I'm a bit more checked-out than normal lol

**Pull request merged**
